# Generated by Django 4.0.6 on 2023-08-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=200, verbose_name='nickname')),
                ('space', models.URLField()),
                ('cookies', models.TextField()),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'account',
                'db_table': 'account',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='nickname')),
                ('space', models.URLField()),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'author',
                'db_table': 'author',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('duration', models.IntegerField(help_text='seconds')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilibili.author')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
                'db_table': 'video',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('channel', models.CharField(blank=True, max_length=200, null=True, verbose_name='channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bilibili.video')),
            ],
            options={
                'verbose_name': 'video profile',
                'verbose_name_plural': 'video profile',
                'db_table': 'video_profile',
                'abstract': False,
            },
        ),
    ]
